### ISSUE TITLE
Create an ActionDataDisplay Component and Primitives

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#385] opened 2022-07-11 15:45 UTC
## Overview

With Baal this would always be in the same shape so we can create a reusable component that displays the action data (as long as we can find the ABI).

**Comment by earth2travis** [comment] 2022-07-18 18:47
Duplicate of https://github.com/HausDAO/daohaus-monorepo/issues/404

**Closed** 2022-07-18 18:47 UTC
Labels: haus-components
